# Generated by Django 2.2.4 on 2020-03-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191023_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boookmark',
            field=models.BooleanField(default=False),
        ),
    ]
