# Generated by Django 2.2.4 on 2020-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_boookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boookmark',
            field=models.BooleanField(),
        ),
    ]
