# Generated by Django 2.2.4 on 2020-03-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200319_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boookmark',
            field=models.BooleanField(blank=True),
        ),
    ]
