# Generated by Django 2.2.4 on 2020-04-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dis_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user/image'),
        ),
    ]
