# Generated by Django 2.2.4 on 2020-04-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200405_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dis_pic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
